name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false

jobs:
  mirrorchyan:
    if: ${{ github.repository_owner == 'BaiXiaoTao520' }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: android
            arch: arm64
            filename: 'app-release.apk'

    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ matrix.filename }}
          mirrorchyan_rid: New-ZexNote
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: BaiXiaoTao520
          repo: New-ZexNote
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
